### ISSUE TITLE
Response Error for current-month

### ISSUE THREAD

**Issue by Kiurym** [alexmacarthur/current-year-api#3]
I'm using this API for a discord bot. The current-month link is currently responding with "7" (July) for this month of August (8)
![image](https://github.com/alexmacarthur/current-time-api/assets/142355226/20d06b44-07bf-41ad-a1af-0cf81eaf1df1)

**Comment by alexmacarthur** [comment]
I love that you're using this! The API uses the JS Date object, which returns a zero-based index for the month, so 7 is the correct value for the month of August (and January is 0, etc.): 

<img width="618" alt="image" src="https://github.com/alexmacarthur/current-time-api/assets/8398220/61ac2b7e-4fa7-49a4-bdd8-2b14095eb4d8">
